export const thinkingLists: readonly string[] = [
    "Consulting the pundits",
    "Analyzing the stats",
    "Checking the playbook",
    "Running the numbers",
    "Searching the archives",
    "Gathering insights",
    "Reviewing the match footage",
    "Debating the panel",
    "Crunching the data",
    "Scouting the records",
    "Diving into the history books",
    "Asking the experts",
    "Breaking down the tactics",
    "Pulling up the highlights",
    "Scanning the transfer news",
    "Studying the formations",
    "Checking the injury reports",
    "Looking at the league table",
    "Reviewing head-to-head records",
    "Analyzing player performance",
    "Consulting the coaching staff",
    "Searching for historical parallels",
    "Cross-referencing the statistics",
    "Assessing the tactical setup",
    "Evaluating the evidence",
    "Running a deep analysis",
    "Preparing the verdict",
    "Comparing historical matchups",
    "Reviewing the scouting report",
    "Studying defensive structures",
    "Evaluating offensive chemistry",
    "Simulating match scenarios",
    "Assessing player form",
    "Consulting the record books",
    "Tracking performance metrics",
    "Sifting through the rumor mill",
    "Analyzing the coaching philosophy",
    "Comparing individual matchups",
    "Assessing team chemistry",
    "Reviewing season averages",
    "Evaluating championship odds",
    "Analyzing game pace",
    "Studying opponent tendencies",
    "Comparing roster depth",
    "Reviewing recent form guides",
    "Analyzing offensive schemes",
    "Evaluating draft prospects",
    "Checking the schedule breakdown",
    "Analyzing home-field advantage",
    "Measuring physical conditioning",
    "Studying game tape",
    "Assessing squad rotation",
    "Analyzing championship history",
    "Consulting the rulebook",
    "Simulating league outcomes",
    "Analyzing play-by-play data",
    "Checking pre-game predictions",
    "Comparing head-to-head history",
    "Analyzing defensive matchups",
    "Predicting player impact ratings",
    "Reviewing historical box scores",
    "Evaluating trade rumors",
    "Analyzing tactical adjustments",
    "Consulting sports science data",
    "Assessing roster flexibility",
    "Reviewing tournament seeds",
    "Simulating bracket matchups",
    "Assessing key injuries",
    "Analyzing scoring efficiency",
    "Checking pre-match press conferences",
    "Comparing payrolls and market value",
    "Studying opponent play patterns",
    "Assessing game momentum",
    "Running statistical regressions",
    "Analyzing referee tendencies",
    "Analyzing clutch performance metrics",
    "Evaluating coaching track records",
    "Reviewing seasonal progression charts",
    "Assessing developmental trends",
    "Comparing home vs. away splits",
    "Evaluating fatigue levels",
    "Reviewing replay angles",
    "Analyzing style of play indices",
    "Tracking speed and stamina metrics",
    "Reading the morning headlines",
    "Sifting through post-game quotes",
    "Simulating playoff paths",
    "Analyzing spacing and zone coverage",
    "Evaluating coaching adjustments",
    "Consulting sports medicine updates",
    "Analyzing age-curve projections",
    "Evaluating bench production",
    "Checking the rule changes database",
    "Reviewing pre-match warm-ups",
    "Studying offensive pacing data",
    "Analyzing transition efficiency",
    "Calculating championship win probabilities",
    "Assessing referee profiles",
    "Evaluating strength of schedule metrics",
    "Reviewing post-game media reports",
];